--- #YAML:1.0
name: XML-RSS-LibXML
version: 0.05
author: ~
abstract: XML::RSS with XML::LibXML (parse-only)
license: perl
requires:
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
build_requires:
  Test::More: 0
provides:
  XML::RSS::LibXML:
    file: lib/XML/RSS/LibXML.pm
    version: 0.05
generated_by: Module::Build version 0.2607
